### ISSUE TITLE
the bot does not work for me

### ISSUE THREAD

**Issue by pingbee333** [WardPearce/SourceQueryBot#8]
Hi, the bot throws me this error on heroku 2020-08-19T21: 11: 26.094454 + 00: 00 app [worker.1]: [WARNING]: 'ServerModel' object is not subscriptable and does not show the discord presence.

In pc throws me this error: Please wait I'm closing.
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    client.run("token")
  File "D:\Usuario\Desktop\Programas\lib\site-packages\discord\client.py", line 640, in run
    return future.result()
  File "D:\Usuario\Desktop\Programas\lib\site-packages\discord\client.py", line 621, in runner
    await self.start(*args, **kwargs)
  File "D:\Usuario\Desktop\Programas\lib\site-packages\discord\client.py", line 585, in start
    await self.connect(reconnect=reconnect)
  File "D:\Usuario\Desktop\Programas\lib\site-packages\discord\client.py", line 499, in connect
    await self._connect()
  File "D:\Usuario\Desktop\Programas\lib\site-packages\discord\client.py", line 463, in _connect
    await self.ws.poll_event()
  File "D:\Usuario\Desktop\Programas\lib\site-packages\discord\gateway.py", line 471, in poll_event
    await self.received_message(msg)
  File "D:\Usuario\Desktop\Programas\lib\site-packages\discord\gateway.py", line 425, in received_message
    func(data)
  File "D:\Usuario\Desktop\Programas\lib\site-packages\discord\state.py", line 750, in parse_guild_create
    guild = self._get_create_guild(data)
  File "D:\Usuario\Desktop\Programas\lib\site-packages\discord\state.py", line 725, in _get_create_guild
    guild._from_data(data)
  File "D:\Usuario\Desktop\Programas\lib\site-packages\discord\guild.py", line 297, in _from_data
    self._sync(guild)
  File "D:\Usuario\Desktop\Programas\lib\site-packages\discord\guild.py", line 324, in _sync
    self._add_channel(TextChannel(guild=self, data=c, state=self._state))
  File "D:\Usuario\Desktop\Programas\lib\site-packages\discord\channel.py", line 107, in __init__
    self._update(guild, data)
  File "D:\Usuario\Desktop\Programas\lib\site-packages\discord\channel.py", line 131, in _update
    self._fill_overwrites(data)
  File "D:\Usuario\Desktop\Programas\lib\site-packages\discord\abc.py", line 294, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new'

The errors started from nowhere :/, I use the bot for my game server community, I tried the updated version and it doesn't work either.

**Comment by WardPearce** [comment]
Hey,
Have you installed the latest requirements?

`pip3 install aioquery==1.0.0` 


I'm assuming that's why you're getting this error` [WARNING]: 'ServerModel' object is not subscriptable`

**Comment by WardPearce** [comment]
Re-open the issue if this didn't fix it
